# Generated by Django 4.1.1 on 2022-09-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='zipcode',
        ),
    ]
