# Generated by Django 4.1.1 on 2022-09-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0002_remove_userdata_firstname_remove_userdata_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='email',
            new_name='username',
        ),
    ]
